"use client"

import dynamic from "next/dynamic"
import type { ComponentType } from "react"

// Each demo loads as its own chunk so a page only ships the component it shows.
export const demos: Record<string, ComponentType> = {
  accordion: dynamic(() => import("./accordion-demo")),
  alert: dynamic(() => import("./alert-demo")),
  "alert-dialog": dynamic(() => import("./alert-dialog-demo")),
  "aspect-ratio": dynamic(() => import("./aspect-ratio-demo")),
  attachment: dynamic(() => import("./attachment-demo")),
  avatar: dynamic(() => import("./avatar-demo")),
  badge: dynamic(() => import("./badge-demo")),
  breadcrumb: dynamic(() => import("./breadcrumb-demo")),
  bubble: dynamic(() => import("./bubble-demo")),
  button: dynamic(() => import("./button-demo")),
  "button-group": dynamic(() => import("./button-group-demo")),
  calendar: dynamic(() => import("./calendar-demo")),
  card: dynamic(() => import("./card-demo")),
  carousel: dynamic(() => import("./carousel-demo")),
  chart: dynamic(() => import("./chart-demo")),
  checkbox: dynamic(() => import("./checkbox-demo")),
  collapsible: dynamic(() => import("./collapsible-demo")),
  combobox: dynamic(() => import("./combobox-demo")),
  command: dynamic(() => import("./command-demo")),
  "context-menu": dynamic(() => import("./context-menu-demo")),
  dialog: dynamic(() => import("./dialog-demo")),
  drawer: dynamic(() => import("./drawer-demo")),
  "dropdown-menu": dynamic(() => import("./dropdown-menu-demo")),
  empty: dynamic(() => import("./empty-demo")),
  field: dynamic(() => import("./field-demo")),
  "hover-card": dynamic(() => import("./hover-card-demo")),
  input: dynamic(() => import("./input-demo")),
  "input-group": dynamic(() => import("./input-group-demo")),
  "input-otp": dynamic(() => import("./input-otp-demo")),
  item: dynamic(() => import("./item-demo")),
  kbd: dynamic(() => import("./kbd-demo")),
  label: dynamic(() => import("./label-demo")),
  marker: dynamic(() => import("./marker-demo")),
  menubar: dynamic(() => import("./menubar-demo")),
  message: dynamic(() => import("./message-demo")),
  "message-scroller": dynamic(() => import("./message-scroller-demo")),
  "native-select": dynamic(() => import("./native-select-demo")),
  "navigation-menu": dynamic(() => import("./navigation-menu-demo")),
  pagination: dynamic(() => import("./pagination-demo")),
  popover: dynamic(() => import("./popover-demo")),
  progress: dynamic(() => import("./progress-demo")),
  "radio-group": dynamic(() => import("./radio-group-demo")),
  resizable: dynamic(() => import("./resizable-demo")),
  "scroll-area": dynamic(() => import("./scroll-area-demo")),
  select: dynamic(() => import("./select-demo")),
  separator: dynamic(() => import("./separator-demo")),
  sheet: dynamic(() => import("./sheet-demo")),
  sidebar: dynamic(() => import("./sidebar-demo")),
  skeleton: dynamic(() => import("./skeleton-demo")),
  slider: dynamic(() => import("./slider-demo")),
  sonner: dynamic(() => import("./sonner-demo")),
  spinner: dynamic(() => import("./spinner-demo")),
  switch: dynamic(() => import("./switch-demo")),
  table: dynamic(() => import("./table-demo")),
  tabs: dynamic(() => import("./tabs-demo")),
  textarea: dynamic(() => import("./textarea-demo")),
  toast: dynamic(() => import("./toast-demo")),
  toggle: dynamic(() => import("./toggle-demo")),
  "toggle-group": dynamic(() => import("./toggle-group-demo")),
  tooltip: dynamic(() => import("./tooltip-demo")),
}
